default_config:

logger:
  default: info
  logs:
    custom_components.energyscore: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
#debugpy:
#  start: True
#  wait: True

sensor:
  - platform: energyscore
    name: Heater Energy Score 778
    energy_entity: weather.forecast_home
    price_entity: sun.sun
    unique_id: fknmekfe
  - platform: energyscore
    name: Another great senzor
    energy_entity: sun.sun
    price_entity: sensor.heater_energy_score_778