default_config:

logger:
  default: info
  logs:
    custom_components.powerscore: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
#debugpy:
#  start: True
#  wait: True

sensor:
  - platform: powerscore
    name: Heater Power Score 777
    power_entity: weather.forecast_home
    price_entity: sun.sun
  - platform: powerscore
    name: Another great sensor
    power_entity: sensor.heater_power_score_777
    price_entity: sun.sun