default_config:

logger:
  default: info
  logs:
    custom_components.integration_blueprint: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

sensor:
  - platform: powerscore
    name: Heater Power Score
    price_entity: sensor.sun