name: Version Bump Check
on:
  push:
    branches:
      - '*'

jobs:
  version_bump_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract version from JSON file
        working-directory: ./custom_components/energyscore
        run: |
          cat manifest.json | jq '.version' > current_version.txt
          cat current_version.txt
      - name: Get latest release version
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          # git tag --list 'v[0-9]+\.[0-9]+\.[0-9]+'
          # git describe --abbrev=0 --match='v[0-9]+\.[0-9]+\.[0-9]+' > latest_release_version.txt
          # cat latest_release_version.txt
      - name: Check for version bump
        run: |
          # Extract version numbers from .txt files
          current_version=$(cat current_version.txt | jq -r '.version')
          latest_release_version=$(cat latest_release_version.txt | jq -r '.version')

          # Compare version numbers numerically using the bc command
          if [ $(echo "$current_version > $latest_release_version" | bc) -eq 1 ]; then
            echo "Current version is higher than release version!"
          else
            echo "Current version is not higher than release version."
            exit 1
          fi

