name: Version Bump Check
on:
  push:
    branches:
      - '*'

jobs:
  version_bump_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract version from JSON file
        working-directory: ./custom_components/energyscore
        run: |
          cat -v manifest.json | jq '.version' > current_version.txt
      - name: Get latest release version
        run: |
          git -v tag --sort=-v:refname | head -n 1 > latest_release_version.txt
      - name: Check for version bump
        run: |
          if ! cmp -s current_version.txt latest_release_version.txt; then
            echo "Version bump detected!"
          else
            echo "No version bump detected."
            exit 1
          fi
